[build]
  command = "npm ci && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Settings
[context.production]
  command = "npm ci && npm run build"
