[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect rules for single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
